server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: order-and-payment
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, 
        - id: delivery-management
          uri: http://localhost:8082
          predicates:
            - Path=/deliveries/**, 
        - id: customer-service
          uri: http://localhost:8083
          predicates:
            - Path=/customerInquiries/**, 
        - id: marketing-advertising
          uri: http://localhost:8084
          predicates:
            - Path=/marketingCampaigns/**, 
        - id: it-technology-server-management
          uri: http://localhost:8085
          predicates:
            - Path=/systemManagements/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order-and-payment
          uri: http://orderAndPayment:8080
          predicates:
            - Path=/orders/**, 
        - id: delivery-management
          uri: http://deliveryManagement:8080
          predicates:
            - Path=/deliveries/**, 
        - id: customer-service
          uri: http://customerService:8080
          predicates:
            - Path=/customerInquiries/**, 
        - id: marketing-advertising
          uri: http://marketingAdvertising:8080
          predicates:
            - Path=/marketingCampaigns/**, 
        - id: it-technology-server-management
          uri: http://itTechnologyServerManagement:8080
          predicates:
            - Path=/systemManagements/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
