apiVersion: v1
kind: Service
metadata:
  name: it-technology-server-management
  labels:
    app: it-technology-server-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: it-technology-server-management